site_name: Neutis docs
theme_dir: docstheme/material
site_favicon: favicon.ico
repo_url: https://github.com/emlid/neutis-docs

extra:
  palette:
    primary: 'light blue'
    accent: 'light blue'
  logo: 'img/logo.png'
  social:
    - type: 'github'
      link: 'https://github.com/emlid'
    - type: 'twitter'
      link: 'https://twitter.com/emlidtech'
    - type: 'facebook'
      link: 'https://facebook.com/emlidtech'
google_analytics:
 - UA-49508097-1
 - auto

markdown_extensions:
 - markdown.extensions.admonition
 - markdown.extensions.codehilite(guess_lang=false)
 - markdown.extensions.def_list
 - markdown.extensions.footnotes
 - markdown.extensions.meta
 - markdown.extensions.toc(permalink=true)

pages:
- Introduction : 'index.md'
- First setup: 'intro/flash.md'
- Connectivity: 
    - 'How to connect to Neutis?': 'connectivity/connectivity.md'
    - 'Serial': 'connectivity/serial.md'
    - 'USB-Ethernet': 'connectivity/usb-ssh.md'
    - 'Wi-Fi': 'connectivity/wifi.md'
    - 'Ethernet': 'connectivity/ethernet.md'
